### ISSUE TITLE
你好，运行train.py出现如下问题？

### ISSUE THREAD

**Issue by Wisdom2wisdom** [CarrieLea/RNN_Attention_NMT#1]
Traceback (most recent call last):
  File "E:/program_code/machine_Translation/file_2/RNN_Attention_NMT-main/main.py", line 201, in <module>
    main()
  File "E:/program_code/machine_Translation/file_2/RNN_Attention_NMT-main/main.py", line 154, in main
    all_ = data_preprocess.load_dataset(args.train_data_path, args.dev_data_path, args.test_data_path, \
  File "E:\program_code\machine_Translation\file_2\RNN_Attention_NMT-main\utils\data_preprocess.py", line 28, in load_dataset
    vectors = Vectors(name=src_wordVectors_path)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\MT\lib\site-packages\torchtext\vocab.py", line 280, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\MT\lib\site-packages\torchtext\vocab.py", line 327, in cache
    raise RuntimeError('no vectors found at {}'.format(path))
RuntimeError: no vectors found at .vector_cache\dataset/sgns.renmin.bigram-char

**Comment by PANPANKK** [comment]
我也是这个问题，请问有解决方案嘛？
